---
kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: keycloak-pgsql
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: data
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: keycloak-pgsql
