---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-{{ .Values.myapp.tenantName }}-myapp-provisiondata
  namespace: {{ .Values.myapp.namespace }}
  labels:
    demo.redhat.com/tenant-{{ .Values.tenant.name }}: "true"
  annotations:
    argocd.argoproj.io/sync-options: "Prune=true"
data:
  provision_data: |
    namespace: {{ .Values.myapp.namespace }}
