apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    app.kubernetes.io/part-of: myapp
    tenant: {{ .Values.tenant.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        tenant: {{ .Values.tenant.name }}
    spec:
      containers:
      - name: myapp
        image: registry.access.redhat.com/ubi8/httpd-24:latest
        imagePullPolicy: Always
         ports:
        - containerPort: 8080
          protocol: TCP
          name: http

        - name: html-content
          mountPath: /var/www/html
          readOnly: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

      - name: html-content
        configMap:
          name: myapp-html
