apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    app.kubernetes.io/part-of: myapp
    tenant: {{ .Values.tenant.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        tenant: {{ .Values.tenant.name }}
    spec:
      containers:
      - name: myapp
        image: {{ .Values.image.repository }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http

        - name: html-content
          mountPath: /var/www/html
          readOnly: true

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

      - name: html-content
        configMap:
          name: myapp-html
